name: ConsoleSpamFix
version: '${project.version}'
main: me.luucka.consolespamfix.ConsoleSpamFixPlugin
api-version: 1.18
load: STARTUP
authors: [ Luucka ]
description: Stop the console spam errors.
loadbefore: [LuckPerms]
