name: ConsoleSpamFix
version: '${project.version}'
main: me.luucka.consolespamfix.ConsoleSpamFixPlugin
api-version: 1.19
load: STARTUP
authors: [ LuuckA ]
description: Stop console spam errors.
loadbefore: [ LuckPerms ]
